'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18063
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="BasePrueba")>  _
Partial Public Class DAODataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("BasePruebaConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_ListarCampaña")>  _
	Public Function sp_ListarCampaña() As ISingleResult(Of sp_ListarCampañaResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of sp_ListarCampañaResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_listarEmpresas")>  _
	Public Function sp_listarEmpresas() As ISingleResult(Of sp_listarEmpresasResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of sp_listarEmpresasResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_RegistrarCampaña")>  _
	Public Function sp_RegistrarCampaña(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(50)")> ByVal desc_camp As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal cod_emp As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), desc_camp, cod_emp)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_listarpostulantesCampañas")>  _
	Public Function sp_listarpostulantesCampañas(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal cod_camp As System.Nullable(Of Integer)) As ISingleResult(Of sp_listarpostulantesCampañasResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), cod_camp)
		Return CType(result.ReturnValue,ISingleResult(Of sp_listarpostulantesCampañasResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_listarpostulantesNoCampaña")>  _
	Public Function sp_listarpostulantesNoCampaña(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal cod_camp As System.Nullable(Of Integer)) As ISingleResult(Of sp_listarpostulantesNoCampañaResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), cod_camp)
		Return CType(result.ReturnValue,ISingleResult(Of sp_listarpostulantesNoCampañaResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_AsignarPostulanteCampaña")>  _
	Public Function sp_AsignarPostulanteCampaña(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(20)")> ByVal cod_trab As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal cod_camp As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal cod_emp As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), cod_trab, cod_camp, cod_emp)
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

Partial Public Class sp_ListarCampañaResult
	
	Private _co_camp As Integer
	
	Private _desc_camp As String
	
	Private _co_emp As System.Nullable(Of Integer)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_co_camp", DbType:="Int NOT NULL")>  _
	Public Property co_camp() As Integer
		Get
			Return Me._co_camp
		End Get
		Set
			If ((Me._co_camp = value)  _
						= false) Then
				Me._co_camp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_desc_camp", DbType:="VarChar(50)")>  _
	Public Property desc_camp() As String
		Get
			Return Me._desc_camp
		End Get
		Set
			If (String.Equals(Me._desc_camp, value) = false) Then
				Me._desc_camp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_co_emp", DbType:="Int")>  _
	Public Property co_emp() As System.Nullable(Of Integer)
		Get
			Return Me._co_emp
		End Get
		Set
			If (Me._co_emp.Equals(value) = false) Then
				Me._co_emp = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_listarEmpresasResult
	
	Private _Co_emp As Integer
	
	Private _Des_emp As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Co_emp", DbType:="Int NOT NULL")>  _
	Public Property Co_emp() As Integer
		Get
			Return Me._Co_emp
		End Get
		Set
			If ((Me._Co_emp = value)  _
						= false) Then
				Me._Co_emp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Des_emp", DbType:="VarChar(50)")>  _
	Public Property Des_emp() As String
		Get
			Return Me._Des_emp
		End Get
		Set
			If (String.Equals(Me._Des_emp, value) = false) Then
				Me._Des_emp = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_listarpostulantesCampañasResult
	
	Private _CO_TRAB As String
	
	Private _NO_TRAB As String
	
	Private _AP_PAT_TRAB As String
	
	Private _AP_MAT_TRAB As String
	
	Private _NO_DIRE As String
	
	Private _NO_CUPS As String
	
	Private _CO_AFPS As String
	
	Private _CO_BANC_ABON As String
	
	Private _FG_CIVI As String
	
	Private _CO_NACI As String
	
	Private _CO_DPTO As String
	
	Private _CO_PROV As String
	
	Private _CO_DIST As String
	
	Private _FG_SEXO As String
	
	Private _FG_ESTADO As String
	
	Private _NO_CORREO As String
	
	Private _nombre As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_TRAB", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property CO_TRAB() As String
		Get
			Return Me._CO_TRAB
		End Get
		Set
			If (String.Equals(Me._CO_TRAB, value) = false) Then
				Me._CO_TRAB = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NO_TRAB", DbType:="VarChar(60)")>  _
	Public Property NO_TRAB() As String
		Get
			Return Me._NO_TRAB
		End Get
		Set
			If (String.Equals(Me._NO_TRAB, value) = false) Then
				Me._NO_TRAB = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AP_PAT_TRAB", DbType:="VarChar(30)")>  _
	Public Property AP_PAT_TRAB() As String
		Get
			Return Me._AP_PAT_TRAB
		End Get
		Set
			If (String.Equals(Me._AP_PAT_TRAB, value) = false) Then
				Me._AP_PAT_TRAB = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AP_MAT_TRAB", DbType:="VarChar(30)")>  _
	Public Property AP_MAT_TRAB() As String
		Get
			Return Me._AP_MAT_TRAB
		End Get
		Set
			If (String.Equals(Me._AP_MAT_TRAB, value) = false) Then
				Me._AP_MAT_TRAB = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NO_DIRE", DbType:="VarChar(150)")>  _
	Public Property NO_DIRE() As String
		Get
			Return Me._NO_DIRE
		End Get
		Set
			If (String.Equals(Me._NO_DIRE, value) = false) Then
				Me._NO_DIRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NO_CUPS", DbType:="VarChar(20)")>  _
	Public Property NO_CUPS() As String
		Get
			Return Me._NO_CUPS
		End Get
		Set
			If (String.Equals(Me._NO_CUPS, value) = false) Then
				Me._NO_CUPS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_AFPS", DbType:="VarChar(20)")>  _
	Public Property CO_AFPS() As String
		Get
			Return Me._CO_AFPS
		End Get
		Set
			If (String.Equals(Me._CO_AFPS, value) = false) Then
				Me._CO_AFPS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_BANC_ABON", DbType:="VarChar(23)")>  _
	Public Property CO_BANC_ABON() As String
		Get
			Return Me._CO_BANC_ABON
		End Get
		Set
			If (String.Equals(Me._CO_BANC_ABON, value) = false) Then
				Me._CO_BANC_ABON = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FG_CIVI", DbType:="VarChar(20)")>  _
	Public Property FG_CIVI() As String
		Get
			Return Me._FG_CIVI
		End Get
		Set
			If (String.Equals(Me._FG_CIVI, value) = false) Then
				Me._FG_CIVI = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_NACI", DbType:="VarChar(26)")>  _
	Public Property CO_NACI() As String
		Get
			Return Me._CO_NACI
		End Get
		Set
			If (String.Equals(Me._CO_NACI, value) = false) Then
				Me._CO_NACI = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_DPTO", DbType:="VarChar(26)")>  _
	Public Property CO_DPTO() As String
		Get
			Return Me._CO_DPTO
		End Get
		Set
			If (String.Equals(Me._CO_DPTO, value) = false) Then
				Me._CO_DPTO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_PROV", DbType:="VarChar(26)")>  _
	Public Property CO_PROV() As String
		Get
			Return Me._CO_PROV
		End Get
		Set
			If (String.Equals(Me._CO_PROV, value) = false) Then
				Me._CO_PROV = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_DIST", DbType:="VarChar(26)")>  _
	Public Property CO_DIST() As String
		Get
			Return Me._CO_DIST
		End Get
		Set
			If (String.Equals(Me._CO_DIST, value) = false) Then
				Me._CO_DIST = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FG_SEXO", DbType:="VarChar(10)")>  _
	Public Property FG_SEXO() As String
		Get
			Return Me._FG_SEXO
		End Get
		Set
			If (String.Equals(Me._FG_SEXO, value) = false) Then
				Me._FG_SEXO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FG_ESTADO", DbType:="VarChar(1)")>  _
	Public Property FG_ESTADO() As String
		Get
			Return Me._FG_ESTADO
		End Get
		Set
			If (String.Equals(Me._FG_ESTADO, value) = false) Then
				Me._FG_ESTADO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NO_CORREO", DbType:="VarChar(100)")>  _
	Public Property NO_CORREO() As String
		Get
			Return Me._NO_CORREO
		End Get
		Set
			If (String.Equals(Me._NO_CORREO, value) = false) Then
				Me._NO_CORREO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre", DbType:="VarChar(123)")>  _
	Public Property nombre() As String
		Get
			Return Me._nombre
		End Get
		Set
			If (String.Equals(Me._nombre, value) = false) Then
				Me._nombre = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_listarpostulantesNoCampañaResult
	
	Private _CO_TRAB As String
	
	Private _NO_TRAB As String
	
	Private _AP_PAT_TRAB As String
	
	Private _AP_MAT_TRAB As String
	
	Private _NO_DIRE As String
	
	Private _NO_CUPS As String
	
	Private _CO_AFPS As String
	
	Private _CO_BANC_ABON As String
	
	Private _FG_CIVI As String
	
	Private _CO_NACI As String
	
	Private _CO_DPTO As String
	
	Private _CO_PROV As String
	
	Private _CO_DIST As String
	
	Private _FG_SEXO As String
	
	Private _FG_ESTADO As String
	
	Private _NO_CORREO As String
	
	Private _nombre As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_TRAB", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property CO_TRAB() As String
		Get
			Return Me._CO_TRAB
		End Get
		Set
			If (String.Equals(Me._CO_TRAB, value) = false) Then
				Me._CO_TRAB = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NO_TRAB", DbType:="VarChar(60)")>  _
	Public Property NO_TRAB() As String
		Get
			Return Me._NO_TRAB
		End Get
		Set
			If (String.Equals(Me._NO_TRAB, value) = false) Then
				Me._NO_TRAB = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AP_PAT_TRAB", DbType:="VarChar(30)")>  _
	Public Property AP_PAT_TRAB() As String
		Get
			Return Me._AP_PAT_TRAB
		End Get
		Set
			If (String.Equals(Me._AP_PAT_TRAB, value) = false) Then
				Me._AP_PAT_TRAB = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AP_MAT_TRAB", DbType:="VarChar(30)")>  _
	Public Property AP_MAT_TRAB() As String
		Get
			Return Me._AP_MAT_TRAB
		End Get
		Set
			If (String.Equals(Me._AP_MAT_TRAB, value) = false) Then
				Me._AP_MAT_TRAB = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NO_DIRE", DbType:="VarChar(150)")>  _
	Public Property NO_DIRE() As String
		Get
			Return Me._NO_DIRE
		End Get
		Set
			If (String.Equals(Me._NO_DIRE, value) = false) Then
				Me._NO_DIRE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NO_CUPS", DbType:="VarChar(20)")>  _
	Public Property NO_CUPS() As String
		Get
			Return Me._NO_CUPS
		End Get
		Set
			If (String.Equals(Me._NO_CUPS, value) = false) Then
				Me._NO_CUPS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_AFPS", DbType:="VarChar(20)")>  _
	Public Property CO_AFPS() As String
		Get
			Return Me._CO_AFPS
		End Get
		Set
			If (String.Equals(Me._CO_AFPS, value) = false) Then
				Me._CO_AFPS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_BANC_ABON", DbType:="VarChar(23)")>  _
	Public Property CO_BANC_ABON() As String
		Get
			Return Me._CO_BANC_ABON
		End Get
		Set
			If (String.Equals(Me._CO_BANC_ABON, value) = false) Then
				Me._CO_BANC_ABON = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FG_CIVI", DbType:="VarChar(20)")>  _
	Public Property FG_CIVI() As String
		Get
			Return Me._FG_CIVI
		End Get
		Set
			If (String.Equals(Me._FG_CIVI, value) = false) Then
				Me._FG_CIVI = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_NACI", DbType:="VarChar(26)")>  _
	Public Property CO_NACI() As String
		Get
			Return Me._CO_NACI
		End Get
		Set
			If (String.Equals(Me._CO_NACI, value) = false) Then
				Me._CO_NACI = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_DPTO", DbType:="VarChar(26)")>  _
	Public Property CO_DPTO() As String
		Get
			Return Me._CO_DPTO
		End Get
		Set
			If (String.Equals(Me._CO_DPTO, value) = false) Then
				Me._CO_DPTO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_PROV", DbType:="VarChar(26)")>  _
	Public Property CO_PROV() As String
		Get
			Return Me._CO_PROV
		End Get
		Set
			If (String.Equals(Me._CO_PROV, value) = false) Then
				Me._CO_PROV = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CO_DIST", DbType:="VarChar(26)")>  _
	Public Property CO_DIST() As String
		Get
			Return Me._CO_DIST
		End Get
		Set
			If (String.Equals(Me._CO_DIST, value) = false) Then
				Me._CO_DIST = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FG_SEXO", DbType:="VarChar(10)")>  _
	Public Property FG_SEXO() As String
		Get
			Return Me._FG_SEXO
		End Get
		Set
			If (String.Equals(Me._FG_SEXO, value) = false) Then
				Me._FG_SEXO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FG_ESTADO", DbType:="VarChar(1)")>  _
	Public Property FG_ESTADO() As String
		Get
			Return Me._FG_ESTADO
		End Get
		Set
			If (String.Equals(Me._FG_ESTADO, value) = false) Then
				Me._FG_ESTADO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NO_CORREO", DbType:="VarChar(100)")>  _
	Public Property NO_CORREO() As String
		Get
			Return Me._NO_CORREO
		End Get
		Set
			If (String.Equals(Me._NO_CORREO, value) = false) Then
				Me._NO_CORREO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nombre", DbType:="VarChar(123)")>  _
	Public Property nombre() As String
		Get
			Return Me._nombre
		End Get
		Set
			If (String.Equals(Me._nombre, value) = false) Then
				Me._nombre = value
			End If
		End Set
	End Property
End Class
